/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.rcapp;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public class AppTest {

  @Test
  public void twoPlusTwoIsFour() {
    assertEquals(2 + 2, 4);
  }
}
