/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.rcapp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class AppTest {
    @Test
    public void twoPlusTwoIsFour() {
        assertEquals(2 + 2, 4);
    }
}
