/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend;

import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class AppTest {
    @Test
    public void twoPlusTwoIsFour() {
        assertEquals(2 + 2, 4);
    }
}
