name: Code style verification
"on": [push, pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Verify code style
        run: ./gradlew verGJF