name: Code style verification
"on": [push, pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
          java-package: jdk
      - name: Verify code style
        run: ./gradlew verGJF