name: Daily dataset update
on:
  push:
    branches:
      - master
  schedule:
    # every day at 1am
    - cron: '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
          java-package: jdk
      - name: Build
        run: ./gradlew clean build RecycleMapRuImport
      - name: Perform import
        run: |
          java --enable-preview -jar build/libs/importer.jar