name: Docker Release
on:
  create:
    tags:
      - .*
jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - name: Publish Image to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@2.19
        with:
          name: sammers/rcycle-app
          username: sammers
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: true
          tags: "latest,${{ env.RELEASE_VERSION }}"